In [1]:
import torch

In [4]:
x = torch.empty(5, 3)
x

tensor([[8.4489e-39, 9.6429e-39, 8.4490e-39],
        [9.6429e-39, 9.2755e-39, 1.0286e-38],
        [9.0919e-39, 8.9082e-39, 9.2755e-39],
        [8.4490e-39, 8.9082e-39, 9.1837e-39],
        [1.0561e-38, 9.0918e-39, 1.0469e-38]])

In [5]:
x = torch.rand(5, 3)
x

tensor([[0.3371, 0.6646, 0.0886],
        [0.0506, 0.5952, 0.5127],
        [0.1224, 0.5297, 0.7558],
        [0.9007, 0.7414, 0.6297],
        [0.1740, 0.9845, 0.3123]])

In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [7]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [9]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [10]:
x = torch.rand_like(x, dtype=torch.float)
x

tensor([[0.6945, 0.4510, 0.0766],
        [0.8956, 0.5338, 0.3998],
        [0.6889, 0.9820, 0.0188],
        [0.9845, 0.5386, 0.1747],
        [0.3013, 0.2386, 0.2616]])

In [13]:
x.size()

torch.Size([5, 3])

In [16]:
y = torch.rand(5, 3)
x + y

tensor([[1.0626, 0.7561, 0.4361],
        [1.3266, 0.7162, 0.7873],
        [1.5242, 1.9460, 0.7502],
        [1.3257, 1.3810, 0.4185],
        [0.3568, 0.4078, 0.8792]])

In [17]:
torch.add(x, y)

tensor([[1.0626, 0.7561, 0.4361],
        [1.3266, 0.7162, 0.7873],
        [1.5242, 1.9460, 0.7502],
        [1.3257, 1.3810, 0.4185],
        [0.3568, 0.4078, 0.8792]])

In [18]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[1.0626, 0.7561, 0.4361],
        [1.3266, 0.7162, 0.7873],
        [1.5242, 1.9460, 0.7502],
        [1.3257, 1.3810, 0.4185],
        [0.3568, 0.4078, 0.8792]])

In [22]:
y.add_(x)

tensor([[1.0626, 0.7561, 0.4361],
        [1.3266, 0.7162, 0.7873],
        [1.5242, 1.9460, 0.7502],
        [1.3257, 1.3810, 0.4185],
        [0.3568, 0.4078, 0.8792]])

In [23]:
y

tensor([[1.0626, 0.7561, 0.4361],
        [1.3266, 0.7162, 0.7873],
        [1.5242, 1.9460, 0.7502],
        [1.3257, 1.3810, 0.4185],
        [0.3568, 0.4078, 0.8792]])

In [26]:
y[:, :]

tensor([[1.0626, 0.7561, 0.4361],
        [1.3266, 0.7162, 0.7873],
        [1.5242, 1.9460, 0.7502],
        [1.3257, 1.3810, 0.4185],
        [0.3568, 0.4078, 0.8792]])

In [34]:
y.view(-1, 3, 5)

tensor([[[1.0626, 0.7561, 0.4361, 1.3266, 0.7162],
         [0.7873, 1.5242, 1.9460, 0.7502, 1.3257],
         [1.3810, 0.4185, 0.3568, 0.4078, 0.8792]]])

In [35]:
torch.cuda.is_available()

True

In [37]:
device = torch.device('cuda')
y = torch.ones_like(x, device=device)
x = x.to(device)
z = x + y
print(z)
print(z.to('cpu'))

tensor([[1.6945, 1.4510, 1.0766],
        [1.8956, 1.5338, 1.3998],
        [1.6889, 1.9820, 1.0188],
        [1.9845, 1.5386, 1.1747],
        [1.3013, 1.2386, 1.2616]], device='cuda:0')
tensor([[1.6945, 1.4510, 1.0766],
        [1.8956, 1.5338, 1.3998],
        [1.6889, 1.9820, 1.0188],
        [1.9845, 1.5386, 1.1747],
        [1.3013, 1.2386, 1.2616]])


In [38]:
z.to(torch.double)

tensor([[1.6945, 1.4510, 1.0766],
        [1.8956, 1.5338, 1.3998],
        [1.6889, 1.9820, 1.0188],
        [1.9845, 1.5386, 1.1747],
        [1.3013, 1.2386, 1.2616]], device='cuda:0', dtype=torch.float64)