In [1]:
import torch

In [4]:
x = torch.ones(2, 2)
x.requires_grad = True
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [5]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [6]:
y.grad_fn

In [21]:
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([3060902.2500, 2014117.0000,  184336.3281], grad_fn=<MulBackward0>)
tensor(1753118.5000, grad_fn=<MeanBackward0>)


In [19]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [22]:
out.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [12]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [16]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
y

tensor([-1010.0994,   819.3731,  -247.8819], grad_fn=<MulBackward0>)

In [18]:
gradients = torch.tensor([0.1, 1, 0.0001], dtype=torch.float)
y.backward(gradients)
x.grad

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])

In [23]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print(x.requires_grad)
    print((x ** 2).requires_grad)

True
True
True
False
